[package]
name = "choseong-pullup"
description = "촛엉 올려 쓱이 in Rust"
version = "0.1.1"
authors = ["ylsun <y15un@y15un.dog>"]
license = "MIT"
edition = "2018"
workspace = "../"

[dependencies]
unicode-korean-multitool = { path = "../unicode-korean-multitool", version = "0.2" } # MIT
